# Generated by Django 5.0.1 on 2024-01-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coderandom',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
