# Generated by Django 5.0.1 on 2024-01-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_coderandom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coderandom',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
